version: 2
jobs:
 build:
   branches:
      only:
        - master
   machine: true
   dependencies:
    override:
     - docker info
     - docker build --rm=false -t danka/go-app:latest .
   steps:
     - checkout
     # build and run docker image
     - run: |
         docker login --username=$DOCKER_USERNAME --password=$DOCKER_PWD
         CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o go-app .
         docker build -t danka/go-app:latest .
         docker run --publish 6060:8080 -d --name test danka/go-app
     - run:
          name: test
          command: "curl http://localhost:6060/"
     - run:
          name: test
          command: docker push danka/go-app:latest
